version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 8
    groups:
      storybook:
        patterns:
          - "@storybook*"
          - "storybook"
      eslint:
        patterns:
          - "*eslint*"
      remotion:
        patterns:
          - "*remotion*"
      playwright:
        patterns:
          - "*playwright*"
      vite:
        patterns:
          - "*vite*"
          - "*vitest*"
        exclude-patterns:
          - "@storybook*"