# See https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

name: setup-node
description: 'Setups node to the specific version'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        # Newer versions might fail https://github.com/yarnpkg/berry/issues/4778
        node-version-file: '.nvmrc'
        cache: 'yarn'
    - run: yarn install
      shell: bash
