# See https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

name: run-playwright
description: 'Installs, caches, runs and store artifacts of Playwright'

inputs:
  packagescript:
    required: true
    description: 'Script from package.json to run'
  project:
    required: false
    description: 'Playwright project (browser)'
    default: 'chromium'

runs:
  using: 'composite'
  steps:
    - uses: actions/cache@v3
      id: playwright-cache
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}-${{ inputs.project }}
        restore-keys: |
          ${{ runner.os }}-playwright-${{ inputs.project }}
    - run: yarn playwright install --with-deps ${{ inputs.project }}
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      shell: bash
    - run: yarn playwright install-deps ${{ inputs.project }}
      if: steps.playwright-cache.outputs.cache-hit == 'true'
      shell: bash
    - name: CT Test run
      run: yarn ${{ inputs.packagescript }} --project ${{ inputs.project }}
      shell: bash
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: ${{ inputs.packagescript }}-${{ inputs.project }}-test-results
        path: |
          playwright-report
          test-results
