# See https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

name: run-playwright
description: 'Installs, caches, runs and store artifacts of Playwright'

inputs:
  packagescript:
    required: true
    description: 'Script from package.json to run'
  shard:
    required: false
    description: 'which shard to run'
    default: '1'
  shardTotal:
    required: false
    description: 'total number of shards'
    default: '1'
  project:
    required: false
    description: 'Playwright project (browser)'
    default: 'chromium'

runs:
  using: 'composite'
  steps:
    - uses: actions/cache@v4
      id: playwright-cache
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ inputs.project }}
        restore-keys: |
          ${{ runner.os }}-playwright-${{ inputs.project }}
    - run: pnpm playwright install --with-deps chromium ${{ inputs.project }}
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      shell: bash
    - run: pnpm playwright install-deps ${{ inputs.project }}
      if: steps.playwright-cache.outputs.cache-hit == 'true'
      shell: bash
    - uses: nick-fields/retry@v3
      name: CT Test run ${{ inputs.packagescript }} (${{ inputs.project }})
      with:
        timeout_minutes: 20
        max_attempts: 2
        command: pnpm ${{ inputs.packagescript }} --shard=${{ inputs.shard }}/${{ inputs.shardTotal }} --project=${{ inputs.project }} `pnpm ts-node scripts/runFailedPlaywrightTests.ts || ""`
        shell: bash
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: ${{ inputs.packagescript }}-${{ inputs.project }}-${{ inputs.shard }}-test-results
        path: |
          playwright-report
          test-results
          build
