# See https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

name: run-playwright
description: 'Runs and stores artifacts of Playwright'

inputs:
  config:
    required: true
    description: 'Playwright config filename'
  shard:
    required: false
    description: 'which shard to run'
    default: '1'
  shardTotal:
    required: false
    description: 'total number of shards'
    default: '1'
  project:
    required: false
    description: 'Playwright project (browser)'
    default: 'chromium'
  updateSnapshots:
    required: false
    description: 'Whether to pass -u to Playwright'
    default: 'false'

runs:
  using: 'composite'
  steps:
    - run: npx playwright test -c ${{ inputs.config }} ${{ inputs.updateSnapshots == 'true' && '-u' || '' }} --shard=${{ inputs.shard }}/${{ inputs.shardTotal }} --project=${{ inputs.project }}
      shell: bash
      name: 'Run Playwright tests'
    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: test-results-blob-${{ inputs.config }}-${{ inputs.project }}-${{ inputs.shard }}
        path: |
          blob-report
    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: test-results-report-${{ inputs.config }}-${{ inputs.project }}-${{ inputs.shard }}
        path: |
          playwright-report
