
name: run-playwright

# Were we can define the inputs that our action will accept
inputs:
  packagescript:
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'yarn'
    - run: yarn install