/**
 * Every iconify identifier actually used in the app. Kept as a closed list (rather than plain
 * `string`) so a new icon can't be introduced by copy-pasting a slightly different identifier for a
 * role that's already covered by one of these — adding one here is a deliberate, greppable step.
 *
 * The icons are bundled rather than fetched from the Iconify API - scripts/vite-plugin-bundled-icons.ts
 * picks each one listed here out of its `@iconify-json/<prefix>` set.
 */
export const ICON_NAMES = [
  'cib:facebook',
  'cib:github',
  'cib:instagram',
  'ic:baseline-access-time',
  'ic:baseline-add',
  'ic:baseline-arrow-back',
  'ic:baseline-arrow-forward',
  'ic:baseline-arrow-right',
  'ic:baseline-calendar-today',
  'ic:baseline-casino',
  'ic:baseline-check',
  'ic:baseline-check-box',
  'ic:baseline-check-box-outline-blank',
  'ic:baseline-close',
  'ic:baseline-content-copy',
  'ic:baseline-delete',
  'ic:baseline-download',
  'ic:baseline-edit',
  'ic:baseline-error',
  'ic:baseline-expand-more',
  'ic:baseline-fast-forward',
  'ic:baseline-favorite',
  'ic:baseline-fullscreen',
  'ic:baseline-fullscreen-exit',
  'ic:baseline-games',
  'ic:baseline-help',
  'ic:baseline-keyboard',
  'ic:baseline-keyboard-arrow-down',
  'ic:baseline-keyboard-arrow-left',
  'ic:baseline-keyboard-arrow-right',
  'ic:baseline-keyboard-arrow-up',
  'ic:baseline-language',
  'ic:baseline-laptop',
  'ic:baseline-list',
  'ic:baseline-lock-open',
  'ic:baseline-logout',
  'ic:baseline-pause',
  'ic:baseline-people-alt',
  'ic:baseline-person',
  'ic:baseline-phone-android',
  'ic:baseline-phone-iphone',
  'ic:baseline-photo-camera',
  'ic:baseline-play-arrow',
  'ic:baseline-qr-code',
  'ic:baseline-qr-code-2',
  'ic:baseline-refresh',
  'ic:baseline-remove',
  'ic:baseline-search',
  'ic:baseline-send',
  'ic:baseline-settings',
  'ic:baseline-shuffle',
  'ic:baseline-speed',
  'ic:baseline-star',
  'ic:baseline-swap-horiz',
  'ic:baseline-sync',
  'ic:baseline-thumb-down',
  'ic:baseline-thumb-up',
  'ic:baseline-visibility',
  'ic:baseline-visibility-off',
  'ic:baseline-warning',
  'ic:baseline-wifi',
  'ic:outline-check-circle',
  'ic:outline-fiber-new',
  'ic:outline-help',
  'ic:outline-lock',
  'ic:round-people-alt',
  'mdi:arrow-left',
  'mdi:circle',
  'mdi:crown',
  'mdi:qrcode-scan',
  'mdi:warning',
  'mdi:wifi',
] as const;

export type IconName = (typeof ICON_NAMES)[number];
