name: 'Import songs'

on:
  workflow_dispatch:
    inputs:
      user_id:
        description: 'PostHog user IDs (comma separated) to import songs from'
        required: false
        default: ''
      days_from:
        description: 'The days from which to import songs. `2` (so NOW - 48h) by default'
        required: false
        default: ''
      days_to:
        description: 'The days to which to import songs'
        required: false
        default: ''
  schedule:
    - cron: '0 0 * * *'

jobs:
  run_script:
    permissions:
      contents: write # https://github.com/stefanzweifel/git-auto-commit-action?tab=readme-ov-file#usage
    runs-on: ubuntu-latest
    env:
      VITE_APP_POSTHOG_KEY: ${{ secrets.POSTHOG_PAT_KEY }}
      UNVERIFIED_SONGS_ADMIN_URL: ${{ secrets.UNVERIFIED_SONGS_ADMIN_URL || secrets.SHARED_SONGS_ADMIN_URL }}
      UNVERIFIED_SONGS_ADMIN_TOKEN: ${{ secrets.UNVERIFIED_SONGS_ADMIN_TOKEN || secrets.SHARED_SONGS_ADMIN_TOKEN }}
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.GH_PAT_REPOS_WORKFLOW }}
          fetch-depth: 100
      - name: Setup Node
        uses: './.github/templates/setup-node'
      - run: npx playwright install chromium
        timeout-minutes: 3
      - name: Get songs
        if: github.event_name == 'workflow_dispatch'
        run: pnpm ts-node scripts/cicd/github-action-import-songs.ts "${{ github.event.inputs.user_id || secrets.DEFAULT_IMPORT_USER_IDS }}" "${{ github.event.inputs.days_from }}" "${{ github.event.inputs.days_to }}"
      - name: Get songs scheduled
        if: github.event_name == 'schedule'
        run: pnpm ts-node scripts/cicd/github-action-import-songs.ts "${{ secrets.DEFAULT_IMPORT_USER_IDS }}" "" ""
      - name: Update stats
        run: pnpm ts-node scripts/generate-song-stats.ts
      - name: Update popularity index
        run: pnpm ts-node scripts/generate-song-popularity-index.ts
      - name: Auto commit songs
        id: auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: 'Update songs from user ${{ github.event.inputs.user_id }}'
