name: Cypress Tests

on: [push]

jobs:
    cypress-run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Install
              uses: actions/setup-node@v2
              with:
                  node-version: '16'
                  cache: 'yarn'
            - run: yarn install
            - run: yarn test
            - name: Cypress run
              uses: cypress-io/github-action@v2
              with:
                  build: yarn run build
                  start: yarn start:production
              env:
                  DISABLE_ESLINT_PLUGIN: true
            - uses: actions/upload-artifact@v3
              with:
                  name: cypress-test-results
                  path: |
                      cypress/screenshots
                      cypress/videos
                      cypress/integration/__image_snapshots__
